<a href="https://colab.research.google.com/github/pmap1986/Paula_Alfonso_KC/blob/main/Taller_Paula_Alfonso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy en el cmd

ERROR: Could not find a version that satisfies the requirement en (from versions: none)
ERROR: No matching distribution found for en


In [ ]:
import numpy as np


1. Como es posible obtener el siguiente resultado:
array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr1= np.insert(arr,(1,3,5,7,9),-1)
#print(arr1)
np.delete(arr1,(2,5,8,11,-1))


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.where (arr%2 == 1, -1, arr)


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

2.	Tienen el siguiente input:
np.arange(10)
Como se puede hacer para obtener el siguiente resultado:
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])



In [ ]:
a=np.arange(10)
a=a.reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

3.	Con base en el siguiente input:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
Obtener el siguiente resultado
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])


In [91]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1) 

np.concatenate((a,b),axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

*4.	Con base en el siguiente input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Obtener el siguiente output
array([2, 4])*

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

5.	Del siguiente input:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
Obtener el siguiente output
array([1,2,3,4])


In [4]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
#c = np.concatenate((a,b),axis=0)


np.setdiff1d(a, b)




array([1, 2, 3, 4])

6.	Con el siguiente input:
a = np.array([2, 6, 1, 9, 10, 3, 27])
Obtener:
(array([6, 9, 10]),)


In [16]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
b=(sorted(a))
print(b)
print('----')
np.array(b[3:-1])








[1, 2, 3, 6, 9, 10, 27]
----


array([ 6,  9, 10])

7.	Invertir las filas de un arreglo de matriz 2D
arr = np.arange(9).reshape(3,3)
Output deseado:
array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])


In [24]:
 arr = np.arange(9).reshape(3,3)
 print(arr)
print('----')
 print(np.flip(arr, axis=0))
print('----')
 np.array(arr[::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
----
[[6 7 8]
 [3 4 5]
 [0 1 2]]
----


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])